Fixed the text center in pie box
iobio/iobio-charts pull request #114
Opened 2024-09-19 20:24 UTC by YangQi007

2024-09-30 19:53 UTC, anderspitman requested changes
@YangQi007 I think this should be closed in favor of other PRs right?

2024-10-16 20:59 UTC, YangQi007 commented
> @YangQi007 I think this should be closed in favor of other PRs right?

Sorry, I missed this comment. I think it was because of my email notification.

Yes, I think we can close this one. The misplaced text in the percent chart on the Safari will be solved in the iobio.viz repo.

2024-10-23 17:43 UTC, anderspitman commented
@YangQi007 this should be good to go once you merge the latest version of iobio.viz.

2024-10-23 21:21 UTC, anderspitman approved these changes

2024-10-23 21:21 UTC, merged