Updated the loading indicator
iobio/iobio-charts pull request #79
Opened 2024-08-07 23:53 UTC by YangQi007

2024-08-08 16:42 UTC, anderspitman requested changes
@YangQi007 rather than duplicating the indicator code, would it be possible to make it into an `iobio-loading-indicator` web component? Assuming you're using the same one everywhere...

2024-08-08 17:51 UTC, anderspitman commented
Converting SVG to PNG might prove rather difficult. And it could start to bloat the app size as well. Since those images are controlled by the index.html and not the iobio-charts library, I would expect them to work fine. Can you open another PR that shows the problem?

2024-08-09 00:04 UTC, anderspitman requested changes
Looks great overall. Just one name change request

2024-08-09 00:04 UTC, anderspitman commented on loading_indicator.js
> +customElements.define('loading-indicator', LoadingIndicator);
Can you rename the registered component to `iobio-loading-indicator`?

2024-08-09 15:58 UTC, merged

2024-08-09 15:58 UTC, anderspitman commented
@YangQi007 don't forget to request a review when you're ready for me to re-check PRs. Pretty sure you were done with this one so I merged. Great work!

2024-08-09 16:11 UTC, YangQi007 commented
> @YangQi007 don't forget to request a review when you're ready for me to re-check PRs. Pretty sure you were done with this one so I merged. Great work!

Sorry, I forgot to request a review again. I always thought it would send notifications automatically.

2024-08-09 16:19 UTC, anderspitman commented
It does send notifications of commits pushed, but I don't know if you're finished until you request review. For example you might just be pushing commits to back up your work before lunch but planning to push more commits later before requesting review.